spring:
  application:
    name: laundry
  profiles:
    active: standalone
  messages:
    basename: messages/message
    use-code-as-default-message: false
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

server:
  port: 8080
  tomcat:
    threads:
      max: 512
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    session:
      timeout: 30m

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include:
          - health
          - prometheus
          - loggers
      path-mapping:
        health: healthy
  health:
    redis:
      enabled: false
  endpoint:
    loggers:
      enabled: true

logging:
  level:
    com.laundry.laundrysample: debug
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    org.hibernate.orm.jdbc.bind: trace
    #org.hibernate.orm.jdbc.extract: trace

feign:
  httpclient:
    disableSslValidation: true
  client:
    config:
      default:
        connect-timeout: 30000
        read-timeout: 30000
        loggerLevel: FULL

---
spring:
  config:
    activate:
      on-profile: standalone
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
    password:
    hikari:
      maximum-pool-size: 50
  jpa:
    hibernate.ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.H2Dialect


